#!/bin/bash

. resolve

docker build -t carqualifier/aerospike-server-enterprise:${VERSION:-latest} .

if [ $PUSH ] && [ $PUSH -eq 1 ]; then
  docker push carqualifier/aerospike-server-enterprise:${VERSION:-latest}
fi
